openapi: 3.0.0
info:
  title: User API
  version: 0.0.0
tags: []
paths:
  /pets:
    get:
      operationId: IPets_list
      parameters:
        - name: limit
          in: query
          required: true
          schema:
            type: integer
            format: int32
          explode: false
        - name: skip
          in: query
          required: true
          schema:
            type: integer
            format: int32
          explode: false
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
components:
  schemas:
    Direction:
      type: string
      enum:
        - north
        - east
        - south
        - west
    Dog:
      type: object
      properties:
        address:
          type: string
          default: wild
    Foo:
      type: number
      enum:
        - 1
        - 10
        - 100
        - 1000
    Pet:
      type: object
      required:
        - id
        - name
        - createdAt
        - age
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          minLength: 4
          maxLength: 8
        createdAt:
          type: string
          default: hello
        age:
          type: integer
          format: int16
          minimum: 0
          maximum: 130
servers:
  - url: https://example.com/api
    description: production
    variables: {}
