openapi: 3.0.0
info:
  title: (title)
  version: 0.0.0
tags: []
paths: {}
components:
  schemas:
    Direction:
      type: string
      enum:
        - north
        - east
        - south
        - west
    Foo:
      type: number
      enum:
        - 1
        - 10
        - 100
        - 1000
    Pet:
      type: object
      required:
        - id
        - name
        - createdAt
        - age
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          minLength: 4
          maxLength: 8
        createdAt:
          type: string
        age:
          type: integer
          format: int16
          minimum: 0
          maximum: 130
