openapi: 3.0.0
info:
  title: (title)
  version: 0.0.0
tags: []
paths: {}
components:
  schemas:
    ASample:
      type: object
      required:
        - b
      properties:
        a:
          type: array
          items:
            type: string
        b:
          type: array
          items:
            type: string
          default:
            - sample1
            - sample2
        c:
          type: array
          items:
            type: string
          default: []
    BSample:
      type: object
      required:
        - b
      properties:
        a:
          type: boolean
        b:
          type: boolean
          default: true
        c:
          type: boolean
          default: false
    ISample:
      type: object
      required:
        - b
      properties:
        a:
          type: integer
          format: int32
        b:
          type: integer
          default: 42
        c:
          type: number
          default: 3.14
    SSample:
      type: object
      required:
        - b
      properties:
        a:
          type: string
        b:
          type: string
          default: サンプル文字列
        c:
          type: string
          default: サンプル文字列
